-- A. CRUD Operations -- 
-- 1. Insert a new customer
insert into Customers (customer_name, phone_no) 
values ("abc xyz", "34567876545");

-- 2. Update customer phone number
UPDATE Customers 
SET 
    phone_no = '9090909090'
WHERE
    customer_id = 1;

-- 3. Delete a customer
DELETE FROM Customers 
WHERE
    customer_id = 456;
    
-- 4. Display all customers
SELECT 
    *
FROM
    Customers;

-- B. Menu Queries --
-- 5. Display menu sorted by price
SELECT 
    *
FROM
    Menu_Items
ORDER BY price;

-- 6. Find menu items above ₹300
SELECT 
    *
FROM
    Menu_Items
WHERE
    price > 300;
    
-- 7. Display only beverages
SELECT 
    *
FROM
    Menu_Items
WHERE
    category_id = 4;
    
-- 8. Increase all menu prices by 10%
UPDATE Menu_Items 
SET 
    price = price * 1.10;
    
-- C. Customer Queries --
-- 9. Find customer by name
SELECT 
    *
FROM
    Customers
WHERE
    customer_name = 'Vaishnavi Kane';
    
-- 10. Customers whose name starts with A
SELECT 
    *
FROM
    Customers
WHERE
    customer_name LIKE 'A%';
    
-- 11. Customers ending with "Patil"
SELECT 
    *
FROM
    Customers
WHERE
    customer_name LIKE '%Patil';

-- D. Order Queries --
-- 12. Display today's orders
SELECT 
    *
FROM
    Orders
WHERE
    DATE(order_date) = CURDATE();

-- 13. Find pending orders
SELECT 
    *
FROM
    Orders
WHERE
    order_status = 'Pending';

-- 14. Count pending orders
SELECT 
    COUNT(*)
FROM
    Orders
WHERE
    order_status = 'Pending';

-- 15. Update order status
UPDATE Orders 
SET 
    order_status = 'Completed'
WHERE
    order_id = 16;
    
-- E. Payment Queries.--
-- 16. Total revenue
SELECT 
    SUM(amount)
FROM
    Payments;

-- 17. Average bill
SELECT 
    AVG(amount)
FROM
    Payments;

-- 18. Highest bill
SELECT 
    MAX(amount)
FROM
    Payments;

-- 19. Lowest bill
SELECT 
    MIN(amount)
FROM
    Payments;

-- 20. Count UPI payments
SELECT 
    COUNT(*)
FROM
    Payments
WHERE
    payment_method = 'UPI';

-- F. GROUP BY Questions --
-- 21. Number of orders per table
SELECT 
    table_id, COUNT(*) AS total_order
FROM
    Orders
GROUP BY table_id;

-- 22. Total revenue by payment method
SELECT 
    payment_method, sum(amount)
FROM
    Payments
GROUP BY payment_method;

-- 23. Category-wise menu count
SELECT 
    category_id, COUNT(*)
FROM
    Menu_Items
GROUP BY category_id;

-- 24. Number of customers using each payment method
SELECT 
    payment_method, COUNT(*)
FROM
    Payments
GROUP BY payment_method;

-- G. HAVING Clause --
-- 25. Items ordered more than 5 times
SELECT 
    item_id, SUM(quantity)
FROM
    Order_Details
GROUP BY item_id
HAVING SUM(quantity) > 5;

-- 26. Payment methods collecting more than ₹5000 
SELECT 
    payment_method, SUM(amount)
FROM
    Payments
GROUP BY payment_method
HAVING SUM(amount) > 15000;

-- H. Subqueries --
-- 27. Most expensive menu item
SELECT 
    *
FROM
    Menu_Items
WHERE
    price = (SELECT 
            MAX(price)
        FROM
            Menu_Items);

-- 28. Cheapest item
SELECT 
    *
FROM
    Menu_Items
WHERE
    price = (SELECT 
            MIN(price)
        FROM
            Menu_Items);

-- 29. Customers whose bill is above average
SELECT 
    *
FROM
    Payments
WHERE
    amount > (SELECT 
            AVG(amount)
        FROM
            Payments);

-- I. LEFT JOIN
-- 30. Show all customers even if they haven't placed an order
SELECT 
    c.customer_name, o.order_id
FROM
    Customers c
      left JOIN
    Orders o ON c.customer_id = o.customer_id;

-- J. RIGHT JOIN --
-- 31. Show all orders and customer names
SELECT 
    c.customer_name, o.order_id
FROM
    Customers c
      right JOIN
    Orders o ON c.customer_id = o.customer_id;

-- K. Multi-Table JOIN --
-- 32. Complete Restaurant Report
SELECT 
    c.customer_name,
    m.item_name,
    od.quantity,
    p.amount,
    o.order_status
FROM
    Customers c
        JOIN
    Orders o ON c.customer_id = o.customer_id
        JOIN
    Order_Details od ON o.order_id = od.order_id
        JOIN
    Menu_Items m ON od.item_id = m.item_id
        JOIN
    Payments p ON o.order_id = p.order_id;

-- L. Revenue Analysis
-- 33. Revenue generated by each menu item













